sonar.projectKey=vampi-api
sonar.projectName=VAmPI - Vulnerable API
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/tests/**,**/venv/**,**/__pycache__/**,**/node_modules/**

sonar.python.version=3.9
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
